spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    username: root
    password: root
    url: jdbc:mysql://188.131.254.195/demo01?useSSL=false&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: i18n.login
com:
  tucker:
    manage:
      length: 6
      url: "/"